[versions]

minSdk = "21"
targetSdk = "35"
complileSdk = "35"
java = "21"

# Kotlin
kotlin = "2.0.20"
coroutines = "1.9.0"
ksp = "2.0.20-1.0.25"
serialization = "1.7.3"
datetime = "0.6.1"

# decompose
decompose = "3.2.0"

# AndroidX
activity = "1.9.3"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
core = "1.15.0"
datastore = "1.1.1"
fragment = "1.8.5"
lifecycle = "2.8.7"
room = "2.6.1"
vectordrawable = "1.2.0"
workmanager = "2.10.0"

# Compose
compose = "1.7.6"
material3 = "1.3.1"
vkompose = "0.6.2-k2"
decomposer = "main-SNAPSHOT"
coil = "3.0.4"

# Google
material = "1.12.0"
accompanist = "0.36.0"

# Test
junit = "4.13.2"
test_core = "1.6.1"
test_rules = "1.6.1"
test_junit = "1.2.1"
test_runner = "1.6.2"
truth = "1.0.1"
benchmark_junit = "1.3.3"
kakaocup = "0.0.2"
espresso = "3.6.1"

#
agp = "8.7.3"

hyperion = "0.9.31"
subsampling = "3.10.0"
timber = "5.0.1"

# For Internet
jsoup = "1.18.1"
okio = "3.9.1"
okhttp = "4.12.0"
ktor = "3.0.3"

graphfity = "1.0.0"
detekt = "1.21.0"

[libraries]
# Gradle Plugins
gradlePlugin_decomposer = { module = "com.github.takahirom:decomposer", version.ref = "decomposer" }
gradlePlugin_kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin_android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin_graphfity = { module = "com.github.ivancarras:graphfity-plugin", version.ref = "graphfity" }

# Kotlin
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

# Room
room_runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room_ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room_paging = { module = "androidx.room:room-paging", version.ref = "room" }

# Lifecycle
lifecycle_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle_common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }

# Work Manager
work_runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }
work_gcm = { module = "androidx.work:work-gcm", version.ref = "workmanager" }
work_multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workmanager" }

# Main Android
core = { module = "androidx.core:core-ktx", version.ref = "core" }
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectordrawable" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

subsampling = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version.ref = "subsampling" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Accompanist
permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# For Internet
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp_loging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
ktor_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor_res = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor_auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor_content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Compose
compose_ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose_ui_tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose_ui_tooling_preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose_runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose_runtime_saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version.ref = "compose" }
compose_animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose" }
compose_foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose_foundation_layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "compose" }
compose_material_icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "compose" }
compose_material_icons_ext = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose_coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
compose_coil_network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

hyperion-core = { module = "com.willowtreeapps.hyperion:hyperion-core", version.ref = "hyperion" }
hyperion-crash = { module = "com.willowtreeapps.hyperion:hyperion-crash", version.ref = "hyperion" }

# Tests
junit = { module = "junit:junit", version.ref = "junit" }
test_core = { module = "androidx.test:core-ktx", version.ref = "test_core" }
test_rules = { module = "androidx.test:rules", version.ref = "test_rules" }
test_junit = { module = "androidx.test.ext:junit-ktx", version.ref = "test_junit" }
test_runner = { module = "androidx.test:runner", version.ref = "test_runner" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
benchmark_junit = { module = "androidx.benchmark:benchmark-junit4", version.ref = "benchmark_junit" }
compose_junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose_manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
kakaocup = { module = "io.github.kakaocup:compose", version.ref = "kakaocup" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
coroutines = ["coroutines_core", "coroutines_android"]
room = ["room_ktx", "room_paging", "room_runtime"]
compose = ["compose_ui", "compose_ui_tooling", "compose_ui_tooling_preview", "compose_runtime", "compose_animation",
    "compose_foundation", "compose_foundation_layout", "compose_material_icons", "compose_material_icons_ext",
    "compose_material3", "compose_coil", "compose_coil_network"]
accompanist = ["permissions", "webview"]
hyper = ["hyperion-core", "hyperion-crash"]
tests = ["test_core", "test_rules", "test_junit", "test_runner", "compose_junit", "kakaocup", "espresso"]
ktor = ["ktor_core", "ktor_okhttp", "ktor_logging", "ktor_res", "ktor_auth", "ktor_content", "ktor_json"]
decompose = ["decompose", "decompose-extensions"]

[plugins]
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
graphfity = { id = "com.github.ivancarras.graphfity", version.ref = "graphfity" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vkompose = { id = "com.vk.vkompose", version.ref = "vkompose" }
